### ISSUE TITLE
Update of Centers

### ISSUE THREAD

**Issue by vanzytay** [singlasahil14/loss-exps#1]
Hi, 

Thanks for the amazing experiments.

I was just wondering about whether the centers are actually updated during training.

If they are, could you point out to me where they are updated, namely, I noticed that the center update op is not run in any session or control ops. Could you clarify on that?

Thanks!

**Comment by dinggd** [comment]
Hi
I believe center is updated in the train.py file  function namely _center_loss_fn where it get a variable namely “centers” as I can recall and not requiring gradients, that’s where the centers are stored and updates as center loss is updated.  
Hope this can help. 
Cheers 
Nate
